spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: qq
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.allow_update_outside_transaction: true # figure out no transaction is in progress
