CREATE TABLE REFROG.PRODUCT_DETAIL_HKP(
DETAIL_SEQ NUMERIC(18) NOT NULL PRIMARY KEY,
MASTER_SEQ NUMERIC(18) NOT NULL,
PRODUCT_NAME VARCHAR(200) NOT NULL,
QUANTITY NUMERIC(18),
UNIT_PRICE NUMERIC(18,3),
AMOUNT NUMERIC(18,3),
CREATE_TIME TIMESTAMP NOT NULL,
UPDATE_TIME TIMESTAMP
);
